# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: api-db
    ports:
      - 5432:5432

  adminer: # Tool to access via UI
    image: adminer
    restart: always
    environment: 
      ADMINER_DESIGN: hydra
    ports:
      - 8000:8000